# Generated by Django 5.0.3 on 2024-03-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name="Nom d'utilisateur")),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge')),
                ('can_be_contacted', models.BooleanField(default=False, verbose_name='Peut être contacté')),
                ('can_data_be_shared', models.BooleanField(default=False, verbose_name='Peut partager les données')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membre du personnel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
