# Generated by Django 5.0.3 on 2024-04-03 11:15

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=23, validators=[API.models.validate_age]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='can_be_contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_data_be_shared',
            field=models.BooleanField(default=False),
        ),
    ]
