# Generated by Django 5.0.3 on 2024-03-04 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_issue'),
        ('authentication', '0003_alter_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.issue')),
            ],
        ),
    ]
